<?php
// $ php GuzzleHandlerStack.php

require_once 'autoload.php';

use TwitterStreaming\Tracker;
use TwitterStreaming\Endpoints;
use TwitterStreaming\Extensions;

(new Tracker)
    // Add the new extension. See the file MyGuzzleMiddleware.php
    ->addExtension(Extensions\MyGuzzleMiddleware::class)

    // User endpoint
    ->endpoint(Endpoints\UserEndpoint::class)

    // Method generated by my custom extension
    ->sayHelloBeforeTheRequest()

    // Method generated by my custom extension
    ->notifyWhenResponseIsComplete()

    // Track the tweets
    ->track(function ($tweet) {
        // Print the tweet object
        // Before this part, you'll see a "hello" string
        print_r($tweet);
    });
