<?php
// $ php WorkingWithBaseBehaviors.php

require_once 'autoload.php';

use TwitterStreaming\Tracker;
use TwitterStreaming\Endpoints;
use TwitterStreaming\Extensions;

/**
 * Take a look the file MyCustomBehavior.php for more details
 */
(new Tracker)
    ->registerExtension(Extensions\MyCustomBehavior::class)

    // User endpoint
    ->endpoint(Endpoints\UserEndpoint::class)

    // Method generated by my custom extension
    ->youCannotSayThat()

    // Track the tweets
    ->track(function ($tweet) {
        // Print the tweet object
        print_r($tweet);
    });
